name: taodan
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  connectivity: ^0.4.9
  shared_preferences: ^0.5.8
  fluttertoast: ^7.1.1
  fluro: ^1.7.7
  provider: ^4.3.2
  flutter_screenutil: ^3.1.0
  rxdart: ^0.24.1
  stacked: ^1.7.6
  device_info: ^0.4.2+6
  package_info: ^0.4.1
  json_annotation: ^3.0.1
  flutter_easyrefresh: ^2.1.5
  bloom_ad: ^1.0.1
  uuid: ^2.2.2
  crypto: ^2.1.5
  badges: ^1.1.1
  image_picker: ^0.6.7+7
  modal_bottom_sheet: ^0.2.0+1
  webview_flutter: ^0.3.22
  permission_handler: ^5.0.1+1
  image_cropper: ^1.3.1
  cached_network_image: ^2.3.2+1
  marquee: ^1.6.1
  percent_indicator: "^2.1.7+2"




  common_info:
    path: plugins/common_info
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.4.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/test/
  - assets/images/amount/
  - assets/images/dialog/
  - assets/images/common/
  - assets/images/mine/
  - assets/images/index/
  - assets/images/breeder/
  - assets/images/sign/
  - assets/images/login/
  - assets/images/bottomnav/
  - assets/images/reward/
  - assets/images/throwing_egg/
  - assets/json/
